### ISSUE TITLE
Part 1 is reproducible (with some help of ChatGPT), part 2 not

### ISSUE THREAD

**Issue by AnnekeV** [javimangal/preoperative-atelectasis#1]
**1. What project did you reproduce (include the link!)?**
 
-> this one
 
**2. Does the project have the following on its Github repository:**
 
- [x] A Readme with information about the project
- [x] A license
- [x] Citation information
- [x] Requirements for running the code (dependencies)
- [x] An understandable folder structure
 
**3. What did you appreciate about the project's repository?**
 
->
 
**4. Do you have any suggestions for improvement to the repo?**
 
-> What do I need to run exactly? Not so familar with R so can't make sense of which file
-> says sth on how to install dependencies
-> first data was not there
-> error in package : rnaturalearthhires
-> Error in value[[3L]](cond) : 
  Failed to install the rnaturalearthhires package.
  Please try installing the package for yourself using the following command: 
     devtools::install_github("ropensci/rnaturalearthhires")

-> also an error with kaleido scope
**5. Did you manage to run the project successfully?**
 
- [ ] Yes
- [x] Largely (Part 1 yes, part 2 no)
- [ ] No
- [ ] Other:
 
**6. What went right?**
 
-> i could find the run button
 
**7. What did you need to adjust for the project to (try to) run?**
 
- [ ] I had to install dependencies that were clearly indicated in the requirements/readme
- [x] I had to install dependencies that were not indicated anywhere
- [ ] I had to change the code in some places
- [ ] Other:
 
**8. Where did you have to give up reproducing this repo (if applicable)?**
 
->
 
**9. Did you have to go into the code?**
 
- [x] Yes 
- [ ] No
- [ ] I didn't have to, but I had time left/was intrigued, so I did it anyway!
 
**10. If you looked at the code: what did you like?**
 
-> it was clear for me what was the error, the data, and secondly installing the package, and i asked ChatGPT to help me out
 
**11. If you looked at the code, what would be a single line of advice you want to pass on to its author:**
 
->
 
**12. Any final comments to the author:**
 
->
 
**11. Do you think the class will benefit from a live demo of the reproduction of this project? Why/what can we learn?**
 
->
 
----

**Comment by javimangal** [comment]
Hi, Anneke. Thank you for pointing out these issues, which I have addressed alongside the progress of the project. I believe these issuas are now solve. 

Best, 
Javier

**Comment by javimangal** [comment]
Hi, Anneke. Thank you for pointing out these issues, which I have addressed alongside the progress of the project. I believe these issues are now solved.

Best,
Javier
